---
output: html_document
---

<!-- Leaderboard.md is generated from Leaderboard.Rmd. Please edit that file -->


```{r, results = 'hide', echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(drake)
library(readr)
library(DT)
```

```{r}
loadd(result_table)
loadd(config)
result_table = rowwise(result_table) %>% 
  mutate(score_number = ifelse(is.numeric(scores), scores, Inf), message = ifelse(is.character(scores), scores, ''))
board = result_table %>% arrange(score_number) %>% select(pseudonym, readme_ok, score = score_number, message)
```

# Leaderboard for `r config$competition_name`

```{r}
datatable(board)
```


  * *readme_ok*: was there a README.md publicly available at github.com/`<github handle>`/`r config$competition_name` ?  (If false, then the repo hasn't been created yet or the handle is incorrect)
  * *score*: Score of submitted predictions (lower is better).
  * *message*: Error message if predictions couldn't be found or parsed.
